# Generated by Django 4.2 on 2025-11-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
        ('equipos', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traslado', models.DateTimeField()),
                ('justificacion', models.TextField()),
                ('usuario_registro', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='equipos.equipo')),
                ('sede_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_destino', to='sedes.sede')),
                ('sede_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_origen', to='sedes.sede')),
                ('servicio_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_destino', to='servicios.servicio')),
                ('servicio_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_origen', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Historial de Traslado',
                'verbose_name_plural': 'Historial de Traslados',
                'db_table': 'historial_traslados',
                'ordering': ['-fecha_traslado'],
            },
        ),
    ]
