# Generated by Django 4.2.18 on 2025-11-23 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('calibracion', 'Calibración'), ('calificacion', 'Calificación'), ('verificacion', 'Verificación')], max_length=50)),
                ('mes_mantenimiento', models.IntegerField(help_text='Mes del mantenimiento (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio_mantenimiento', models.IntegerField(help_text='Año del mantenimiento', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('descripcion', models.TextField()),
                ('realizado_por', models.CharField(max_length=150)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario_registro', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historial de Mantenimientos',
                'db_table': 'historial_mantenimientos',
                'ordering': ['-anio_mantenimiento', '-mes_mantenimiento'],
            },
        ),
    ]
