# Generated by Django 4.2 on 2025-11-22 23:07

import django.core.validators
from django.db import migrations, models


def migrar_fechas_a_mes_anio(apps, schema_editor):
    """Migra datos de fecha_mantenimiento a mes/año"""
    HistorialMantenimiento = apps.get_model('historial_mantenimientos', 'HistorialMantenimiento')
    
    for mantenimiento in HistorialMantenimiento.objects.all():
        if mantenimiento.fecha_mantenimiento:
            mantenimiento.mes_mantenimiento = mantenimiento.fecha_mantenimiento.month
            mantenimiento.anio_mantenimiento = mantenimiento.fecha_mantenimiento.year
            mantenimiento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('historial_mantenimientos', '0001_initial'),
    ]

    operations = [
        # Primero agregar los nuevos campos con defaults temporales
        migrations.AddField(
            model_name='historialmantenimiento',
            name='mes_mantenimiento',
            field=models.IntegerField(
                default=1, 
                help_text='Mes del mantenimiento (1-12)', 
                validators=[
                    django.core.validators.MinValueValidator(1), 
                    django.core.validators.MaxValueValidator(12)
                ]
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='anio_mantenimiento',
            field=models.IntegerField(
                default=2024, 
                help_text='Año del mantenimiento', 
                validators=[
                    django.core.validators.MinValueValidator(1900), 
                    django.core.validators.MaxValueValidator(2100)
                ]
            ),
            preserve_default=True,
        ),
        
        # Migrar datos existentes
        migrations.RunPython(
            code=migrar_fechas_a_mes_anio,
            reverse_code=migrations.RunPython.noop
        ),
        
        # Eliminar el campo antiguo
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='fecha_mantenimiento',
        ),
        
        # Actualizar opciones del modelo
        migrations.AlterModelOptions(
            name='historialmantenimiento',
            options={
                'ordering': ['-anio_mantenimiento', '-mes_mantenimiento'], 
                'verbose_name': 'Historial de Mantenimiento', 
                'verbose_name_plural': 'Historial de Mantenimientos'
            },
        ),
        
        # Remover defaults (ahora los campos son obligatorios sin default)
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='mes_mantenimiento',
            field=models.IntegerField(
                help_text='Mes del mantenimiento (1-12)', 
                validators=[
                    django.core.validators.MinValueValidator(1), 
                    django.core.validators.MaxValueValidator(12)
                ]
            ),
        ),
        migrations.AlterField(
            model_name='historialmantenimiento',
            name='anio_mantenimiento',
            field=models.IntegerField(
                help_text='Año del mantenimiento', 
                validators=[
                    django.core.validators.MinValueValidator(1900), 
                    django.core.validators.MaxValueValidator(2100)
                ]
            ),
        ),
    ]
