# Generated by Django 5.2.8 on 2025-11-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='proximo_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimo_mantenimiento',
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_calibracion_anual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_fabricante_anual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_metrologica_anual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50),
        ),
    ]
