# Generated by Django 4.2 on 2025-11-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_rango_trabajo_alter_equipo_clasificacion_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='corriente',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='en_garantia',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='error_maximo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_fabricacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_fin_garantia',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='forma_adquisicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_calibracion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_metrologica',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='guia_rapida',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='hoja_vida',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='humedad_relativa',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='instructivo_manejo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='magnitud',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='manual_operacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='manual_servicio',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nit_proveedor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='otros',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='protocolo_mto_preventivo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='rango_equipo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='rango_trabajo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='registro_importacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='requiere_calibracion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='requiere_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='valor_compra',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='voltaje',
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Baja', 'Baja'), ('En Mantenimiento', 'En Mantenimiento')], default='Activo', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('nit_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('en_garantia', models.BooleanField(default=False)),
                ('fecha_fin_garantia', models.DateField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, choices=[('Compra', 'Compra'), ('Apoyo Tecnológico', 'Apoyo Tecnológico'), ('Donación', 'Donación'), ('Convenio', 'Convenio')], max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_adquisicion', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionMetrologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitud', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('error_maximo', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_mantenimiento', models.BooleanField(default=False)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('requiere_calibracion', models.BooleanField(default=False)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_calibracion', models.DateField(blank=True, null=True)),
                ('proxima_calibracion', models.DateField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_metrologica', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_vida', models.BooleanField(default=False)),
                ('registro_importacion', models.BooleanField(default=False)),
                ('manual_operacion', models.BooleanField(default=False)),
                ('manual_servicio', models.BooleanField(default=False)),
                ('guia_rapida', models.BooleanField(default=False)),
                ('protocolo_mto_preventivo', models.BooleanField(default=False)),
                ('frecuencia_metrologica', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.CharField(blank=True, max_length=50, null=True)),
                ('corriente', models.CharField(blank=True, max_length=50, null=True)),
                ('humedad_relativa', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_funcionamiento', to='equipos.equipo')),
            ],
        ),
    ]
