# Generated by Django 5.2.8 on 2025-11-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_equipo_frecuencia_mantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_calibracion_anual',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_fabricante_anual',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='frecuencia_metrologica_anual',
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_mantenimiento_calibracion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_mantenimiento_fabricante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_mantenimiento_metrologico',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
