# Generated by Django 5.2.8 on 2025-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipo_frecuencia_calibracion_anual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),

        # --- REMOCIONES ---
        migrations.RemoveField(model_name='equipo', name='accesorios'),
        migrations.RemoveField(model_name='equipo', name='alimentacion_electrica'),
        migrations.RemoveField(model_name='equipo', name='apoyo_tecnico'),
        migrations.RemoveField(model_name='equipo', name='capacidad'),
        migrations.RemoveField(model_name='equipo', name='clasificacion_biomedica'),
        migrations.RemoveField(model_name='equipo', name='clasificacion_uso'),
        migrations.RemoveField(model_name='equipo', name='codigo_inventario'),
        migrations.RemoveField(model_name='equipo', name='costo_adquisicion'),
        migrations.RemoveField(model_name='equipo', name='created_at'),
        migrations.RemoveField(model_name='equipo', name='documento_adquisicion'),
        migrations.RemoveField(model_name='equipo', name='estado'),
        migrations.RemoveField(model_name='equipo', name='fecha_instalacion'),
        migrations.RemoveField(model_name='equipo', name='flujo'),
        migrations.RemoveField(model_name='equipo', name='frecuencia_mantenimiento_calibracion'),
        migrations.RemoveField(model_name='equipo', name='frecuencia_mantenimiento_fabricante'),
        migrations.RemoveField(model_name='equipo', name='frecuencia_mantenimiento_metrologico'),
        migrations.RemoveField(model_name='equipo', name='humedad'),
        migrations.RemoveField(model_name='equipo', name='manual_despiece'),
        migrations.RemoveField(model_name='equipo', name='manual_partes'),
        migrations.RemoveField(model_name='equipo', name='manual_usuario'),
        migrations.RemoveField(model_name='equipo', name='numero_acta'),
        migrations.RemoveField(model_name='equipo', name='numero_contrato'),
        migrations.RemoveField(model_name='equipo', name='observaciones'),
        migrations.RemoveField(model_name='equipo', name='otros_documentos'),
        migrations.RemoveField(model_name='equipo', name='periodicidad_calibracion'),
        migrations.RemoveField(model_name='equipo', name='periodicidad_calificacion'),
        migrations.RemoveField(model_name='equipo', name='planos'),
        migrations.RemoveField(model_name='equipo', name='potencia'),
        migrations.RemoveField(model_name='equipo', name='presion'),
        migrations.RemoveField(model_name='equipo', name='protocolo_preventivo'),
        migrations.RemoveField(model_name='equipo', name='proveedor'),
        migrations.RemoveField(model_name='equipo', name='rango_trabajo'),
        migrations.RemoveField(model_name='equipo', name='rpm'),
        migrations.RemoveField(model_name='equipo', name='servicio'),
        migrations.RemoveField(model_name='equipo', name='tecnologia_predominante'),
        migrations.RemoveField(model_name='equipo', name='tipo_calibracion'),
        migrations.RemoveField(model_name='equipo', name='updated_at'),
        migrations.RemoveField(model_name='equipo', name='velocidad'),
        migrations.RemoveField(model_name='equipo', name='vida_util'),

        # --- CAMPOS NUEVOS (corregidos) ---

        migrations.AddField(
            model_name='equipo',
            name='clasificacion_ips',
            field=models.CharField(
                choices=[
                    ('IND', 'Industrial'),
                    ('BIO', 'Biomédico'),
                    ('GASES', 'Gases medicinales')
                ],
                max_length=10,
                null=True,
                blank=True,
                default=None,
            ),
        ),

        migrations.AddField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.CharField(
                choices=[
                    ('Docencia', 'Docencia'),
                    ('Investigación', 'Investigación'),
                    ('Extensión', 'Extensión'),
                    ('Mixto', 'Mixto')
                ],
                max_length=20,
                null=True,
                blank=True,
                default=None,
            ),
        ),

        migrations.AddField(
            model_name='equipo',
            name='codigo_ecri',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='codigo_interno',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='corriente',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='fecha_fabricacion',
            field=models.DateField(null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='frecuencia_calibracion',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='humedad_relativa',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='nit_proveedor',
            field=models.CharField(max_length=20, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='nombre_proveedor',
            field=models.CharField(max_length=150, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='numero_documento',
            field=models.CharField(max_length=50, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='otros',
            field=models.TextField(null=True, blank=True),
        ),

        migrations.AddField(
            model_name='equipo',
            name='propietario',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='protocolo_mto_preventivo',
            field=models.BooleanField(null=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='tiempo_vida_util',
            field=models.IntegerField(null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='tipo_documento',
            field=models.CharField(max_length=50, null=True, blank=True, default=None),
        ),

        migrations.AddField(
            model_name='equipo',
            name='valor_compra',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True, default=None),
        ),

        # ----- ALTER FIELDS -----

        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(
                choices=[
                    ('I', 'Clase I'),
                    ('IIa', 'Clase IIa'),
                    ('IIb', 'Clase IIb'),
                    ('III', 'Clase III')
                ],
                max_length=10,
                null=True,
                blank=True,
                default=None
            ),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='codigo_ips',
            field=models.CharField(max_length=20, null=True, blank=True, default='pendiente'),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='dimensiones',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(null=True, blank=True),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='forma_adquisicion',
            field=models.CharField(
                choices=[
                    ('Compra', 'Compra'),
                    ('Apoyo Tecnológico', 'Apoyo Tecnológico'),
                    ('Donación', 'Donación'),
                    ('Convenio', 'Convenio')
                ],
                max_length=50,
                null=True,
                blank=True,
                default=None
            ),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='frecuencia_metrologica',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='nombre_equipo',
            field=models.CharField(max_length=200),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='proceso',
            field=models.CharField(max_length=150, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='registro_invima',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='requiere_mantenimiento',
            field=models.BooleanField(null=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(max_length=150, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.CharField(max_length=100),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(max_length=100, null=True, blank=True, default=None),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='temperatura',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),

        migrations.AlterField(
            model_name='equipo',
            name='ubicacion_fisica',
            field=models.CharField(max_length=200, null=True, blank=True, default=None),
        ),

        migrations.AlterModelTable(
            name='equipo',
            table=None,
        ),
    ]
