# Generated by Django 4.2 on 2025-11-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('equipos', '0003_remove_equipo_corriente_remove_equipo_dimensiones_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE equipos_equipo SET responsable = NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='usuarios.usuario'),
        ),
    ]
