# Generated by Django 5.2.8 on 2025-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_equipo_options_remove_equipo_accesorios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_ips',
            field=models.CharField(blank=True, choices=[('IND', 'Industrial'), ('BIO', 'Biomédico'), ('GASES', 'Gases medicinales')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_misional',
            field=models.CharField(blank=True, choices=[('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Extensión', 'Extensión'), ('Mixto', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_riesgo',
            field=models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIa', 'Clase IIa'), ('IIb', 'Clase IIb'), ('III', 'Clase III')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_ips',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='forma_adquisicion',
            field=models.CharField(blank=True, choices=[('Compra', 'Compra'), ('Apoyo Tecnológico', 'Apoyo Tecnológico'), ('Donación', 'Donación'), ('Convenio', 'Convenio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nit_proveedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proceso',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='propietario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='protocolo_mto_preventivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='registro_invima',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='requiere_mantenimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tiempo_vida_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='valor_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
