# Generated by Django 4.2 on 2025-11-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_ips', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_ecri', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion_misional', models.CharField(blank=True, choices=[('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Extensión', 'Extensión'), ('Mixto', 'Mixto')], max_length=20, null=True)),
                ('clasificacion_ips', models.CharField(blank=True, choices=[('IND', 'Industrial'), ('BIO', 'Biomédico'), ('GASES', 'Gases medicinales')], max_length=10, null=True)),
                ('clasificacion_riesgo', models.CharField(blank=True, choices=[('I', 'Clase I'), ('IIa', 'Clase IIa'), ('IIb', 'Clase IIb'), ('III', 'Clase III')], max_length=10, null=True)),
                ('registro_invima', models.CharField(blank=True, max_length=100, null=True)),
                ('tiempo_vida_util', models.IntegerField(blank=True, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('nit_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('en_garantia', models.BooleanField(default=False)),
                ('fecha_fin_garantia', models.DateField(blank=True, null=True)),
                ('forma_adquisicion', models.CharField(blank=True, choices=[('Compra', 'Compra'), ('Apoyo Tecnológico', 'Apoyo Tecnológico'), ('Donación', 'Donación'), ('Convenio', 'Convenio')], max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hoja_vida', models.BooleanField(default=False)),
                ('registro_importacion', models.BooleanField(default=False)),
                ('manual_operacion', models.BooleanField(default=False)),
                ('manual_servicio', models.BooleanField(default=False)),
                ('guia_rapida', models.BooleanField(default=False)),
                ('instructivo_manejo', models.BooleanField(default=False)),
                ('protocolo_mto_preventivo', models.BooleanField(default=False)),
                ('frecuencia_metrologica', models.CharField(blank=True, max_length=50, null=True)),
                ('requiere_mantenimiento', models.BooleanField(default=False)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('requiere_calibracion', models.BooleanField(default=False)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=50, null=True)),
                ('magnitud', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('error_maximo', models.CharField(blank=True, max_length=100, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=50, null=True)),
                ('corriente', models.CharField(blank=True, max_length=50, null=True)),
                ('humedad_relativa', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='sedes.sede')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='servicios.servicio')),
            ],
        ),
    ]
