# Generated by Django 4.2 on 2025-11-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='rango_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clasificacion_ips',
            field=models.CharField(blank=True, choices=[('IND', 'IND'), ('BIO', 'BIO'), ('GASES', 'GASES')], max_length=10, null=True),
        ),
    ]
