# Generated by Django 4.2.18 on 2025-11-23 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encargados', '0001_initial'),
        ('equipos', '0004_alter_equipo_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='encargados.encargado'),
        ),
    ]
